title:             Kátia Nakamura
email:             hello@katia.dev
description:       Personal Blog
author:            Kátia Nakamura
baseurl:           "/katia.dev"
url:               "https://katia.dev"

# Social Profiles
twitter_username:  KatiaNakamura
github_username:   katiayn
facebook_username: katiaynakamura

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
